/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "performance-red": "#FF2B2B",
        "deep-crimson": "#930100",
        "void-black": "#050505",
        "obsidian-glass": "rgba(16, 17, 20, 0.55)",
        "carbon-border": "rgba(255, 255, 255, 0.08)",
        "primary": "#FF2B2B",
        "primary-container": "#FF2B2B",
        "on-primary": "#ffffff",
        "on-primary-container": "#5c0000",
        "inverse-primary": "#c00100",
        "secondary": "#ffb4a8",
        "secondary-container": "#980000",
        "on-secondary": "#690000",
        "on-secondary-container": "#ff9f90",
        "tertiary": "#c8c6c7",
        "tertiary-container": "#929091",
        "on-tertiary": "#313031",
        "on-tertiary-container": "#2a292b",
        "surface": "#121414",
        "surface-dim": "#050505",
        "surface-bright": "#38393a",
        "surface-container-lowest": "#080808",
        "surface-container-low": "#0c0c0c",
        "surface-container": "#111111",
        "surface-container-high": "#161616",
        "surface-container-highest": "#1a1a1a",
        "surface-variant": "#333535",
        "surface-tint": "#FF2B2B",
        "on-surface": "#e2e2e2",
        "on-surface-variant": "#ebbbb4",
        "on-background": "#e2e2e2",
        "background": "#050505",
        "inverse-surface": "#e2e2e2",
        "inverse-on-surface": "#2f3131",
        "outline": "rgba(255, 255, 255, 0.08)",
        "outline-variant": "#603e39",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "on-primary-fixed": "#410000",
        "on-primary-fixed-variant": "#930100",
        "secondary-fixed": "#ffdad4",
        "secondary-fixed-dim": "#ffb4a8",
        "on-secondary-fixed": "#410000",
        "on-secondary-fixed-variant": "#930000",
        "tertiary-fixed": "#e5e2e3",
        "tertiary-fixed-dim": "#c8c6c7",
        "on-tertiary-fixed": "#1c1b1d",
        "on-tertiary-fixed-variant": "#474648",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "panel-gap": "1.5rem",
        "grid-margin": "2.5rem",
        "gutter-md": "2rem",
        "bento-unit": "160px",
      },
      fontFamily: {
        "display-hero": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "data-lg": ["JetBrains Mono", "monospace"],
        "data-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "data-lg": ["18px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "data-sm": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
