-- Staff Permissions Table
CREATE TABLE IF NOT EXISTS `staff_permissions` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `staff_id` INT UNSIGNED NOT NULL,
  -- Module Toggles
  `perm_dashboard` TINYINT(1) NOT NULL DEFAULT 1,
  `perm_leads` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_customers` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_bookings` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_advance_bookings` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_job_cards` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_quick_jobs` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_quotations` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_invoices` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_payments` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_inventory` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_reports` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_marketing` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_commissions` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_settings` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_staff_management` TINYINT(1) NOT NULL DEFAULT 0,
  -- Sub-level permission flags (granular control)
  `perm_job_cards_edit` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_job_cards_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_job_cards_complete` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_invoices_create` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_payments_record` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_leads_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_leads_assign` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_customers_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_inventory_edit` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_reports_revenue` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_reports_accounts` TINYINT(1) NOT NULL DEFAULT 0,
  `perm_reports_salary` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `unique_staff` (`staff_id`),
  FOREIGN KEY (`staff_id`) REFERENCES `staff`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
